from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
RAW_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"

# Snowflake connection (DEV / ETL)
SNOWFLAKE_DEV_ETL_ACCOUNT = "sf29869.north-europe.azure"
SNOWFLAKE_DEV_ETL_USER = "STRAT_DEV_USER_ETL"
SNOWFLAKE_DEV_ETL_PASSWORD = "Stratusertallinn35"
SNOWFLAKE_DEV_ETL_ROLE = "STRAT_DEV_ROLE_ETL"
SNOWFLAKE_DEV_ETL_WAREHOUSE = "STRAT_DEV_WH_ETL"

SNOWFLAKE_DEV_DATABASE = "STRAT_DEV_DB"
SNOWFLAKE_DEV_SCHEMA_STAGING = "STAGING"
SNOWFLAKE_DEV_STAGE_STAGING = "MY_STAGE"
SNOWFLAKE_DEV_FILE_FORMAT_PXWEB_CSV = "file_format_csv_comma_doublequote_enclosure"

SNOWFLAKE_DEV_TABLE_TAI_PKH2_ST1 = "TAI_PKH2_ST1"

