MERGE INTO TECHNICAL.LOG tgt
USING (
    SELECT
        %s::NUMBER(38,0) AS EXTRACT_ID,
        %s::VARCHAR AS STEP_NAME,
        %s::VARCHAR AS SOURCE_ID,
        %s::VARCHAR AS SOURCE_FILE,
        %s::VARCHAR AS TARGET_TABLE,
        %s::VARCHAR AS STATUS,
        %s::VARCHAR AS ERROR_MESSAGE
) src
ON tgt.EXTRACT_ID = src.EXTRACT_ID
   AND tgt.STEP_NAME = src.STEP_NAME
   AND tgt.SOURCE_ID = src.SOURCE_ID
WHEN MATCHED THEN UPDATE SET
    SOURCE_FILE = src.SOURCE_FILE,
    TARGET_TABLE = src.TARGET_TABLE,
    STATUS = src.STATUS,
    ERROR_MESSAGE = src.ERROR_MESSAGE,
    LOADED_TS = CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9))
WHEN NOT MATCHED THEN INSERT (
    EXTRACT_ID,
    STEP_NAME,
    SOURCE_ID,
    SOURCE_FILE,
    TARGET_TABLE,
    STATUS,
    ERROR_MESSAGE
)
VALUES (
    src.EXTRACT_ID,
    src.STEP_NAME,
    src.SOURCE_ID,
    src.SOURCE_FILE,
    src.TARGET_TABLE,
    src.STATUS,
    src.ERROR_MESSAGE
);
