USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE STRAT_DEV_DB;
USE SCHEMA ODS;

CREATE TABLE IF NOT EXISTS ods.lk_pkh2_sex (
    sex_id NUMBER(38,0) AUTOINCREMENT,
    sex_label VARCHAR(100) NOT NULL,
    loaded_ts TIMESTAMP_NTZ(9) DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9)),
    CONSTRAINT pk_ods_lk_pkh2_sex PRIMARY KEY (sex_id),
    CONSTRAINT uk_ods_lk_pkh2_sex UNIQUE (sex_label)
);
